default_environment: dev
project_id: 019b7916-fe65-7a10-9076-09291e966f99
include_paths:
- ./extract/mongo-extract-jsondocs.yml
- ./extract/mongo-extract-mapped.yml
- ./load/duckdb-loader.yml
- ./load/csv-loader.yml
- ./transform/mongo-maper.yml
environments:
- name: dev
- name: prod

jobs:
- name: mongo-duckdb-mapped
  tasks:
  - tap-mongodb--mapped flatten-mongo target-duckdb--mapped
- name: mongo-duckdb-jsondocs
  tasks:
  - tap-mongodb--jsondocs target-duckdb--jsondocs
