default_environment: dev
project_id: 019b7916-fe65-7a10-9076-09291e966f99
include_paths:
- ./extract/mongo-extract-jsondocs.yml
- ./extract/mongo-extract-mapped.yml
- ./load/duckdb-loader.yml
- ./load/csv-loader.yml
- ./transform/mongo-maper.yml

environments:
- name: dev
  # Local DuckDB for development and testing
  config:
    plugins:
      loaders:
      - name: target-duckdb--jsondocs
        config:
          path: ${MELTANO_PROJECT_ROOT}/output/duckdb/warehouse.duckdb
      - name: target-duckdb--mapped
        config:
          path: ${MELTANO_PROJECT_ROOT}/output/duckdb/warehouse.duckdb

- name: prod
  # MotherDuck cloud for production
  config:
    plugins:
      loaders:
      - name: target-duckdb--jsondocs
        config:
          path: md:carbonlensmd
          token: ${MOTHERDUCK_TOKEN}
      - name: target-duckdb--mapped
        config:
          path: md:carbonlensmd
          token: ${MOTHERDUCK_TOKEN}
  env:
    MOTHERDUCK_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuZWVxYXNpZmF6YWRhM0BnbWFpbC5jb20iLCJtZFJlZ2lvbiI6ImF3cy11cy1lYXN0LTEiLCJzZXNzaW9uIjoiYW5lZXFhc2lmYXphZGEzLmdtYWlsLmNvbSIsInBhdCI6ImZFcG9HVmF1b213dWFtOE04d0dJRzRSVFpjTi1rNFV1bW9lM0NFODQ2TUEiLCJ1c2VySWQiOiJmNDc0ODBhNy1lMGFkLTQ5YWMtYjhlYy1jZDYzYWYyY2YwNDMiLCJpc3MiOiJtZF9wYXQiLCJyZWFkT25seSI6ZmFsc2UsInRva2VuVHlwZSI6InJlYWRfd3JpdGUiLCJpYXQiOjE3NjgxNDI0Nzd9.JpJFTC6IaleJZ4CCwLFEjY-aXOZ7wEafxldOKma6538

jobs:
- name: mongo-duckdb-mapped
  tasks:
  - tap-mongodb--mapped flatten-mongo target-duckdb--mapped
- name: mongo-duckdb-jsondocs
  tasks:
  - tap-mongodb--jsondocs target-duckdb--jsondocs
- name: mongo-csv--mapped
  tasks:
  - tap-mongodb--mapped flatten-mongo target-csv

schedules:
- name: hourly-load-mapped
  interval: '@hourly'
  job: mongo-duckdb-mapped
- name: hourly-load-direct
  interval: '@hourly'
  job: mongo-duckdb-jsondocs
plugins:
  utilities:
  - name: airflow
    variant: apache
    pip_url: git+https://github.com/meltano/airflow-ext.git@main apache-airflow==2.10.5 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.10.5/constraints-no-providers-${MELTANO__PYTHON_VERSION}.txt
